# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grootui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GrootUi(object):
    def setupUi(self, GrootUi):
        GrootUi.setObjectName("GrootUi")
        GrootUi.resize(1328, 910)
        self.centralwidget = QtWidgets.QWidget(GrootUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1321, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/gui/fram(1).jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 250, 311, 311))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/gui/3nOo.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 295, 55, 141))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 110, 331, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:/gui/BigheartedVagueFoal-size_restricted.gif"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(900, 170, 391, 231))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:/gui/—Pngtree— frames technology futuristic interface_5479025.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 610, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1000, 200, 221, 61))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(970, 310, 221, 61))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 200, 411, 401))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:/gui/VJl.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(960, 400, 261, 291))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:/gui/f889323d87ae92dbd5da3b1193708dc3.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 610, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        GrootUi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GrootUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1328, 26))
        self.menubar.setObjectName("menubar")
        GrootUi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GrootUi)
        self.statusbar.setObjectName("statusbar")
        GrootUi.setStatusBar(self.statusbar)

        self.retranslateUi(GrootUi)
        QtCore.QMetaObject.connectSlotsByName(GrootUi)

    def retranslateUi(self, GrootUi):
        _translate = QtCore.QCoreApplication.translate
        GrootUi.setWindowTitle(_translate("GrootUi", "MainWindow"))
        self.label_3.setText(_translate("GrootUi", "TextLabel"))
        self.pushButton.setText(_translate("GrootUi", "run"))
        self.pushButton_2.setText(_translate("GrootUi", "QUIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GrootUi = QtWidgets.QMainWindow()
    ui = Ui_GrootUi()
    ui.setupUi(GrootUi)
    GrootUi.show()
    sys.exit(app.exec_())
